AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ParamBucketName:
    Description: Name of the bucket
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ParamBucketName
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the sample Amazon S3 bucket with a logging configuration.